/*******************************************************
 * Copyright (C) 2019, Aerial Robotics Group, Hong Kong University of Science and Technology
 * 
 * This file is part of VINS.
 * 
 * Licensed under the GNU General Public License v3.0;
 * you may not use this file except in compliance with the License.
 *******************************************************/

#pragma once

#include <rclcpp/rclcpp.hpp>
#include <vector>
#include <eigen3/Eigen/Dense>
#include "../utility/utility.h"
#include <opencv2/opencv.hpp>
#include <opencv2/core/eigen.hpp>
#include <fstream>
#include <map>

using namespace std;

#define ROS_INFO RCUTILS_LOG_INFO
#define ROS_WARN RCUTILS_LOG_WARN
#define ROS_ERROR RCUTILS_LOG_ERROR

const double FOCAL_LENGTH = 460.0;
const int WINDOW_SIZE = 10;
const int NUM_OF_F = 1000;
//#define UNIT_SPHERE_ERROR

extern double INIT_DEPTH;
extern double MIN_PARALLAX;
extern int ESTIMATE_EXTRINSIC;

extern int USE_GPU;
extern int USE_GPU_ACC_FLOW;
extern int USE_GPU_CERES;

extern double ACC_N, ACC_W;
extern double GYR_N, GYR_W;

extern std::vector<Eigen::Matrix3d> RIC;
extern std::vector<Eigen::Vector3d> TIC;
extern Eigen::Vector3d G;

extern double BIAS_ACC_THRESHOLD;
extern double BIAS_GYR_THRESHOLD;
extern double SOLVER_TIME;
extern int NUM_ITERATIONS;
extern int USE_KITTI_Z_MOTION_PRIOR;
extern double KITTI_Z_MOTION_PRIOR_WEIGHT;
extern std::string EX_CALIB_RESULT_PATH;
extern std::string VINS_RESULT_PATH;
extern std::string OUTPUT_FOLDER;
extern std::string IMU_TOPIC;
extern double TD;
extern int ESTIMATE_TD;
extern int ROLLING_SHUTTER;
extern int ROW, COL;
extern int NUM_OF_CAM;
extern int STEREO;
extern int USE_IMU;
extern int MULTIPLE_THREAD;
// pts_gt for debug purpose;
extern map<int, Eigen::Vector3d> pts_gt;

extern std::string IMAGE0_TOPIC, IMAGE1_TOPIC;
extern std::string FISHEYE_MASK;
extern std::vector<std::string> CAM_NAMES;
extern int MAX_CNT;
extern int MIN_DIST;
extern double F_THRESHOLD;
extern int SHOW_TRACK;
extern int FLOW_BACK;
extern int FEATURE_TRACKER_TYPE;
extern std::string YOLOPOINT_LIGHTGLUE_EXTRACTOR_MODEL_PATH;
extern std::string YOLOPOINT_LIGHTGLUE_MATCHER_MODEL_PATH;
extern std::string YOLOPOINT_LIGHTGLUE_EXTRACTOR_TRT_CACHE_PATH;
extern std::string YOLOPOINT_LIGHTGLUE_MATCHER_TRT_CACHE_PATH;
extern std::string YOLOPOINT_FULL_MODEL_PATH;
extern std::string YOLOPOINT_FULL_TRT_CACHE_PATH;
extern int YOLOPOINT_LIGHTGLUE_USE_TENSORRT;
extern int YOLOPOINT_LIGHTGLUE_USE_CUDA;
extern int YOLOPOINT_LIGHTGLUE_LOG_STATS;
extern int YOLOPOINT_LIGHTGLUE_USE_PERSISTENT_KLT_GEOMETRY;
extern int YOLOPOINT_LIGHTGLUE_PERSISTENT_KLT_USE_FUNDAMENTAL_FILTER;
extern int YOLOPOINT_LIGHTGLUE_MAX_KEYPOINTS;
extern int YOLOPOINT_LIGHTGLUE_INPUT_WIDTH;
extern int YOLOPOINT_LIGHTGLUE_INPUT_HEIGHT;
extern int YOLOPOINT_LIGHTGLUE_NMS_RADIUS;
extern int YOLOPOINT_LIGHTGLUE_REMOVE_BORDERS;
extern double YOLOPOINT_LIGHTGLUE_SCORE_THRESHOLD;
extern int YOLOPOINT_OBJECT_DETECTION_ENABLE;
extern double YOLOPOINT_OBJECT_CONFIDENCE_THRESHOLD;
extern double YOLOPOINT_OBJECT_IOU_THRESHOLD;
extern int YOLOPOINT_OBJECT_MAX_DETECTIONS;
extern int YOLOPOINT_DYNAMIC_FEATURE_FILTER_ENABLE;
extern int YOLOPOINT_DYNAMIC_MIN_STATIC_FEATURES;
extern double YOLOPOINT_DYNAMIC_BOX_MARGIN;
extern double YOLOPOINT_LIGHTGLUE_MODEL_KLT_MAX_DISTANCE;
extern double YOLOPOINT_LIGHTGLUE_STEREO_MIN_CORNER_EIGENVALUE;
extern double YOLOPOINT_LIGHTGLUE_STEREO_FACTOR_RESIDUAL_SCALE;
extern double YOLOPOINT_LIGHTGLUE_STEREO_EPIPOLAR_THRESHOLD;
extern double YOLOPOINT_LIGHTGLUE_STEREO_REPROJECTION_THRESHOLD;
extern double YOLOPOINT_LIGHTGLUE_STEREO_MIN_DEPTH;
extern double YOLOPOINT_LIGHTGLUE_STEREO_MAX_DEPTH;
extern int ONLINE_DENSE_MAPPING_ENABLE;
extern int ONLINE_DENSE_MAPPING_USE_SUBMAP_MANAGER;
extern int ONLINE_DENSE_MAPPING_USE_SUBMAP_QUALITY_FILTER;
extern int ONLINE_DENSE_MAPPING_MIN_SUBMAP_POINTS;
extern double ONLINE_DENSE_MAPPING_MIN_VALID_DEPTH_RATIO;
extern double ONLINE_DENSE_MAPPING_MAX_DEPTH_STD;
extern int ONLINE_DENSE_MAPPING_USE_LOCAL_RADIUS_FILTER;
extern double ONLINE_DENSE_MAPPING_RADIUS_FILTER_RADIUS;
extern int ONLINE_DENSE_MAPPING_RADIUS_FILTER_MIN_NEIGHBORS;
extern int ONLINE_DENSE_MAPPING_USE_ACTIVE_SUBMAP_WINDOW;
extern int ONLINE_DENSE_MAPPING_MAX_ACTIVE_SUBMAPS;
extern double ONLINE_DENSE_MAPPING_ACTIVE_RADIUS;
extern int ONLINE_DENSE_MAPPING_USE_POSE_UPDATE_REASSEMBLY;
extern int ONLINE_DENSE_MAPPING_USE_OCCUPANCY_FUSION;
extern int ONLINE_DENSE_MAPPING_OCCUPANCY_MIN_HITS;
extern double ONLINE_DENSE_MAPPING_OCCUPANCY_PROB_HIT;
extern double ONLINE_DENSE_MAPPING_OCCUPANCY_THRESHOLD;
extern int ONLINE_DENSE_MAPPING_KEYFRAME_STRIDE;
extern int ONLINE_DENSE_MAPPING_PIXEL_STEP;
extern int ONLINE_DENSE_MAPPING_MAX_POINTS_PER_KEYFRAME;
extern int ONLINE_DENSE_MAPPING_MAX_TOTAL_POINTS;
extern double ONLINE_DENSE_MAPPING_MIN_DEPTH;
extern double ONLINE_DENSE_MAPPING_MAX_DEPTH;
extern double ONLINE_DENSE_MAPPING_VOXEL_SIZE;
extern double ONLINE_DENSE_MAPPING_RECTIFIED_FOCAL;
extern double ONLINE_DENSE_MAPPING_MIN_DISPARITY;
extern double ONLINE_DENSE_MAPPING_MAX_DISPARITY;
extern double ONLINE_DENSE_MAPPING_MIN_GRADIENT;
extern std::string ONLINE_DENSE_MAPPING_FOUNDATION_MODEL_PATH;
extern int ONLINE_DENSE_MAPPING_FOUNDATION_USE_TENSORRT;
extern int ONLINE_DENSE_MAPPING_FOUNDATION_USE_CUDA;
extern std::string ONLINE_DENSE_MAPPING_FOUNDATION_TRT_CACHE_PATH;
extern int ONLINE_DENSE_MAPPING_FOUNDATION_INPUT_WIDTH;
extern int ONLINE_DENSE_MAPPING_FOUNDATION_INPUT_HEIGHT;
extern std::string ONLINE_DENSE_MAPPING_TOPIC;
extern int LOOP_CLOSURE_ENABLE;
extern int LOOP_CLOSURE_MODE;
extern int LOOP_CLOSURE_MAX_FEATURES;
extern int LOOP_CLOSURE_KEYFRAME_STRIDE;
extern int LOOP_CLOSURE_STM_SIZE;
extern int LOOP_CLOSURE_MAX_DATABASE_SIZE;
extern int LOOP_CLOSURE_TEMPORAL_CONSISTENCY;
extern int LOOP_CLOSURE_CANDIDATE_WINDOW;
extern int LOOP_CLOSURE_MIN_MATCHES;
extern int LOOP_CLOSURE_MIN_INLIERS;
extern int LOOP_CLOSURE_MIN_F_INLIERS;
extern int LOOP_CLOSURE_MIN_GRID_CELLS;
extern int LOOP_CLOSURE_PNP_ITERATIONS;
extern int LOOP_CLOSURE_POSE_GRAPH_ITERATIONS;
extern int LOOP_CLOSURE_MAX_PENDING_KEYFRAMES;
extern int LOOP_CLOSURE_MIN_INTERVAL;
extern int LOOP_CLOSURE_NEIGHBOR_EDGES;
extern int LOOP_CLOSURE_ALLOW_STEREO_FALLBACK;
extern double LOOP_CLOSURE_APPEARANCE_THRESHOLD;
extern double LOOP_CLOSURE_MODEL_APPEARANCE_THRESHOLD;
extern double LOOP_CLOSURE_MATCH_RATIO;
extern double LOOP_CLOSURE_MIN_INLIER_RATIO;
extern double LOOP_CLOSURE_MIN_F_INLIER_RATIO;
extern double LOOP_CLOSURE_MIN_INLIER_SPREAD;
extern double LOOP_CLOSURE_F_RANSAC_THRESHOLD;
extern double LOOP_CLOSURE_PNP_REPROJECTION_ERROR;
extern double LOOP_CLOSURE_MIN_DEPTH;
extern double LOOP_CLOSURE_MAX_DEPTH;
extern double LOOP_CLOSURE_STEREO_MAX_ERROR;
extern double LOOP_CLOSURE_MAX_TRANSLATION;
extern double LOOP_CLOSURE_MAX_ROTATION_DEG;
extern double LOOP_CLOSURE_ODOM_TRANSLATION_WEIGHT;
extern double LOOP_CLOSURE_ODOM_ROTATION_WEIGHT;
extern double LOOP_CLOSURE_LOOP_TRANSLATION_WEIGHT;
extern double LOOP_CLOSURE_LOOP_ROTATION_WEIGHT;
extern double LOOP_CLOSURE_MIN_TRANSLATION_STD;
extern double LOOP_CLOSURE_MAX_TRANSLATION_STD;
extern double LOOP_CLOSURE_MIN_ROTATION_STD_DEG;
extern double LOOP_CLOSURE_MAX_ROTATION_STD_DEG;
extern double LOOP_CLOSURE_GRAPH_MAX_TRANSLATION_ERROR;
extern double LOOP_CLOSURE_GRAPH_MAX_ROTATION_ERROR_DEG;
extern double LOOP_CLOSURE_GRAPH_MAX_NORMALIZED_ERROR;
extern double LOOP_CLOSURE_DUAL_MAX_TRANSLATION_ERROR;
extern double LOOP_CLOSURE_DUAL_MAX_ROTATION_ERROR_DEG;
extern double LOOP_CLOSURE_GRAVITY_WEIGHT;
extern std::string WORLD_FRAME_ID;
extern std::string BODY_FRAME_ID;
extern std::string CAMERA_FRAME_ID;

void readParameters(std::string config_file);

enum SIZE_PARAMETERIZATION
{
    SIZE_POSE = 7,
    SIZE_SPEEDBIAS = 9,
    SIZE_FEATURE = 1
};

enum StateOrder
{
    O_P = 0,
    O_R = 3,
    O_V = 6,
    O_BA = 9,
    O_BG = 12
};

enum NoiseOrder
{
    O_AN = 0,
    O_GN = 3,
    O_AW = 6,
    O_GW = 9
};
